Add check for CHANGELOG edits

diff --git a/.github/test-notebooks.yml b/.github/test-notebooks.yml
--- a/.github/test-notebooks.yml
+++ b/.github/test-notebooks.yml
@@ -47,3 +47,23 @@ jobs:
             python "$script"
           fi
         done
+
+    changelog:
+    name: "Changelog"
+    runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'pull_request' }}
+    steps:
+      - uses: actions/checkout@v4
+      - name: Assert Changelog Edit
+        run: |
+          git fetch origin main:main
+          NUM_ADDED=`git diff --numstat main HEAD CHANGELOG.md | cut -d$'\t' -f1`
+          echo "Changelog differences: $NUM_ADDED"
+          if [ "$NUM_ADDED" -gt "0" ]; then
+            echo "SUCCESS"
+            exit 0
+          else
+            echo "ERROR - Nothing has been added to CHANGELOG.md"
+            exit 1
+          fi
+
